---
jobs:
- name: update-opencontrol-website
  public: true
  serial: true
  plan:
  - get: git-opencontrol-website
    trigger: true
  - task: rebuild-mkdocs
    config:
      platform: linux
      image: "docker:///metal3d/mkdocs"
      inputs:
        - name: git-opencontrol-website
          path: git-opencontrol-website
      outputs:
        - name: built-docs
      run:
        path: sh
        args:
          - -exc
          - "pushd git-opencontrol-website/; mkdocs build -d ../built-docs --clean; popd"

  - put: opencontrol-website
    params:
      manifest: git-opencontrol-website/manifest.yml
      path: built-docs

resources:
- name: git-opencontrol-website
  type: git
  source:
    uri: https://github.com/opencontrol/opencontrol-website.git

- name: opencontrol-website
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: josh@beanpatch.net
    password: {{PWS_PASSWORD}}
    organization: beanpatch
    space: opencontrol
    skip_cert_check: false
